title: The Big Trip
description: 'Around the world in <span class="correction-wrap"><span class="correction-note">356</span><s class="hand-strike">365</s><span class="correction-caret">^</span></span> days'
baseurl: "/thebigtrip"
url: "https://roooms.github.io"

markdown: kramdown

permalink: /:year/:month/:day/:title/

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - convert.py
